# Generated by Django 2.0 on 2017-12-06 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventCreationTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('eventType', models.CharField(max_length=5)),
            ],
        ),
    ]
